### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by jmdugan** [kattouf/ProgressLine#2]
This is exactly what I was seeking, thank you!

The use case I would like to see is a default text display while the original command runs.

so an additional feature request:

a new command-line option to write my own text, and have that text appear as the "right side" of the progressline persistently while it runs.

as in:

#> long-running-command | progressline -d "Updating sources..."

(I made up "-d" for default text, just some kind of option flag)

and the output just remains like this:

✓ 38s ❯ Updating sources...

ideally, this could also work with the matching algorithm, too, so matched line will continue to stream on above lines, leaving the progressline default text as the current (last) line

**Comment by kattouf** [comment]
I'm really glad to hear that you found my utility useful!

I really like your feature request, and I'd love to implement it. However, I'm currently on vacation without my laptop, so I won't be able to work on this until early September.

**Comment by kattouf** [comment]
The feature was added in [version 0.2.2](https://github.com/kattouf/ProgressLine/releases/tag/0.2.2).
